package org.likefly.petrinet.xml;
/**
 * 
 */


import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * @author like
 *
 */
public class OWLPrinter {
	
	public static String fileToString(File s) throws IOException {
		
		if (!s.exists() || s.isDirectory())
            throw new FileNotFoundException("找不到该文件！！！");
		
		try {
			
			BufferedReader in = new BufferedReader(new FileReader(s));
			String str = "";
		
			try {
				
				String stri;
				//int line = 0;
				
				while ((stri = in.readLine()) != null) {
					System.out.println(stri);
					str += stri;
					//++line;
				}
				
				//System.out.println(line);

				return str;
				
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} finally {
				in.close();
			}
			
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return null; 
		
	}
	
	
	public static void outputFile(File s) throws FileNotFoundException {
		
		if (!s.exists() || s.isDirectory())
            throw new FileNotFoundException("找不到该文件！！！");
		
		try {
			
			BufferedReader in = new BufferedReader(new FileReader(s));
			String str;
			
			try {
				
				//int line = 0;
				
				while ((str = in.readLine()) != null) {
					System.out.println(str);
					//++line;
				}
				
				//System.out.println(line);
				
				in.close();
				
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} 
	}
	
	public static void transfer(File aFile, File target) 
		throws FileNotFoundException{ 
		
		if (!aFile.exists() || aFile.isDirectory())
            throw new FileNotFoundException();
		
		try {
			
			BufferedReader in = new BufferedReader(new FileReader(aFile));
			String s;
			StringBuilder sb = new StringBuilder();
			int Flag = 0;

			
			try {
				int line = 0,x = 0;
				
				while ((s = in.readLine()) != null) {
					line++;
					
					if (s.equals("")) {
						//System.out.println("hhh" + Flag);
						Flag++;
					}
					else {
						Flag = 0;
					}
					if ("<!-- Generated by the OWL API (version 3.4.3) http://owlapi.sourceforge.net -->".equals(s))
						break;
					if (Flag == 0) {
						sb.append(s + '\n');
						//System.out.println(s);
						x++;
					}
				}
				
				in.close();
				
				//System.out.println(line + " " + x);
				PrintWriter out = new PrintWriter(
						new BufferedWriter(new FileWriter(target)));
				out.append(sb);
				//return sb.toString();
				out.close();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} 
		
	}

}
